
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root